version: '3'

services:
    brevets:
        build: brevets/.
        command: python flask_brevets.py
        ports:
            - "5002:$BREVETS_PORT"
        depends_on:
            - api
        environment:
            API_ADDR: api
            API_PORT: $API_PORT
            PORT: $BREVETS_PORT
            DEBUG: "True"
        volumes:
          - ./brevets/:/app
    api:
        build: api/.
        command: python flask_api.py
        ports:
            - "5001:$API_PORT"
        depends_on:
            - db
        environment:
            MONGODB_HOSTNAME: db
            PORT: $API_PORT
            DEBUG: "True"
        volumes:
          - ./api/:/app
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
